### PR TITLE
chore: sync fork, bump deps, fix test github action config

### PR DESCRIPTION
**Pull request by coddeys**

### CODE REVIEW

**Review by hiddewie — COMMENTED** [review]
Why can't we switch to the upstream action? 

Is this action even used anywhere?

**Comment by coddeys** [comment]
> Why can't we switch to the upstream action?
> 
> Is this action even used anywhere?

I think we can. I don't know the real reason why does the fork exist so decided to update.

I agree with you let replace with an original one where it's used or maybe even it can be removed.

**Comment by hiddewie** [comment]
The action `zcong1993/setup-timezone` is now allowed, so our repos can switch to that. This fork can be archived or even removed.

**Comment by coddeys** [comment]
- [x] https://github.com/nedap/cupido-push/pull/33
- [x] https://github.com/nedap/hub/pull/823
- [x] https://github.com/nedap/inventory/pull/26
- [x] https://github.com/nedap/groupcare/pull/4715

**Comment by shkm** [comment]
Great work, Dima! Anything left to do for this PR or can we close it?

**Comment by coddeys** [comment]
> Great work, Dima! Anything left to do for this PR or can we close it?

It's not used anywhere so we can close it and the fork can be removed

**Pull request closed without merging**
